#include <gtk/gtk.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <SDL2/SDL.h>
#include <math.h>
#include <SDL2/SDL_image.h>
#include <err.h>
#include <unistd.h>
#include "../GridDetection/hough_transform.h"
#include "../GridDetection/local_threshold.h"
#include "../GridDetection/sobel.h"
#include "../Traitement/contrast.h"
#include "../Traitement/grayscale.h"
#include "../Traitement/noise_reduction.h"
#include "../utils/lines.h"
#include "../utils/linked_list.h"
#include "../utils/splitting.h"
#include "../utils/utils.h"
#include "../SudokuSolver/reader.h"
#include "../SudokuSolver/solver.h"
#include "../SudokuSolver/writer.h"
#include "../SudokuSolver/reassembled.h"
#include "../NN2/digit_network.h"